### ISSUE TITLE
Formulär intresseanmälan kodstuga 

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#27]
I formuläret står det under rubriken "Lägg till deltagare och målsman i kodstuga", det sista ska tas bort och rubriken ska bara vara: "Formulär intresseanmälan kodstuga" 

Det går heller inte att välja vill kodstuga man vill gå på i drop down menyn - första frågan "Mitt barn är ny till programmering och är intresserad av denna kodstuga.

**Comment by thuma** [comment]
Nu är det korrigerat, att det inte gick/går att välja beror på att ingen kodstuga är öppen för anmälan.
