### ISSUE TITLE
Deltagare

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#31]
Inloggad som volontär har jag möjlighet att redigera en deltagares för- och efternamn, samt andra volontärers personuppgifter. Ta bort den behörigheten tack!

**Comment by thuma** [comment]
Det är inga problem att ordna. Ska man kunna ändra sina egna uppgifter?
Tidigare år har volontärer kunna ändra alla namn, det har inte varit något problem?

**Comment by KodStina** [comment]
Vore ju toppen om de kan ändra sina egna uppgifter men inte andras. 
Nej, jag vet, men detta system klarar ju av lite mer på ett smidigare sätt så det vore bra om de hade access bara till det de ska(om det inte tar för mycket tid).

**Comment by thuma** [comment]
Uppdatering finns nu live.
