### ISSUE TITLE
Volontär

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#32]
Önskar möjlighet att lägga till stående roll för volontär som syns bredvid namnet i alla vyer - Volontärsamordnare och Trygghetsombud.

**Comment by thuma** [comment]
Ska det påverka vilka rättigheter de har att ändra / visa saker?
Annars så är det lättaste att skriva in det i namnfältet. Se exempel där jag lagt upp mig själv som volontär på Chalmers Göteborg. Det går så klart att ordna om det är viktigt att det är ett eget fällt.

**Comment by KodStina** [comment]
Nej, det behöver det inte, så det är ju en superbra idé! Kanske att vi framöver vill ge samordnaren mer behörigheter, men det kan vi i så fall ta längre fram(kanske när några volontärer har satt sig in i koden?!).

**Comment by thuma** [comment]
OK, det låter bra stänger denna för nu.
