### ISSUE TITLE
Volontär-access

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#44]
Just nu kan volontärer se kontaktuppgifter till målsman både via "Deltagare" och "Kontaktlista målsman". Under fliken "Kontaktlista målsman" kan de dessutom editera målsmäns information. Detta känns onödigt och lite osäkert. Så ta snälla bort fliken "Kontaktlista målsman" när man är inloggad som volontär.

**Comment by thuma** [comment]
Korrigerat
