### ISSUE TITLE
Volontär

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#45]
Behov av att kunna lägga in en volontär på flera kodstugor, bland annat iom att vi tänkt använda BESK även för lärarkodstugor, och vissa volontärer är med i både barn- och lärarkodstuga. Dessutom smart att kunna lägga till en volontär som "övervakare" av bemanningen och då är det enkelt om vi kan lägga till den personen som volontär med ställa in deltagandet på "nej" vid varje tillfälle och skriva en kommentar om att personen enbart är reserv eller liknande.

**Comment by thuma** [comment]
Denna issue blir: Kunna lägga in en volontär på flera kodstugor.
Skapar ny issue för den andra delen.

**Comment by thuma** [comment]
Förslaget är att det går att skapa 2 volontärer en för varje kodstuga. Men med samma e-post och telefon. Då kan de också ha olika roller så som Reserv, Ledare etc... blir de ok?

**Comment by KodStina** [comment]
Skule det funka så att en volontär då har fler "alias" kopplade till din Slack-användare och att vi kan lägga till så många vi vill? Det låter som en bra lösning! I vissa fall skulle en person kunna behöva ha 4 roller/alias.

**Comment by thuma** [comment]
Nu är detta aktiverat, det går nu at lägga till en volontär i flera kodstugor.
