### ISSUE TITLE
Kodstuga

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#47]
Eventtyper - möjlighet att välja "kodstuga", "lärarkodstuga" eller "Digital Labs" med tillhörande olika texter, standardmailutskick och synlighet på flikar(tex behövs inte "Kontakt målsman" för lärarkodstuga), och även anmälningsformuläret behöver förändras för den eventtypen.

**Comment by thuma** [comment]
Vilken data ska finnas för deltagare i lärarkodsuga?
Förnamn
Efternamn
Epost
Telefon
Skola?
...

**Comment by thuma** [comment]
NahidS kan du tänka dig jobba med denna?

**Comment by NahidS** [comment]
Yes, jag tar det.

**Comment by NahidS** [comment]
Vilka flikar ska vara synligt för varje eventtyp?
Vilken data ska finnas för deltagare för varje eventtyp?

**Comment by thuma** [comment]
Vi väntar med denna till när behovet uppstår igen.
