### ISSUE TITLE
/apply under "Ska deltagaren/deltagarna bjudas in till kodstugan direkt?"

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#49]
Möjlighet att lägga in deltagare med alternativet att inget mail går ut, deltagaren är bekräftad på en gång och dyker upp i BESK som "Ja". (Vet att du och Anna pratade i detta i torsdags som en long term-förbättring)

**Comment by KodStina** [comment]
Uppar denna lite :)

**Comment by thuma** [comment]
Korrigerat
