### ISSUE TITLE
Deltagare

### ISSUE THREAD

**Issue by KodStina** [thuma/BESK#51]
Möjlighet att ladda upp en kommaseparerad csv-fil innehållande användarnamn och lösenord i Scratch till en deltagargrupp och att uppgifterna automatiskt fördelas på deltagarna

**Comment by thuma** [comment]
Jag tror att det går att göra så att BESKen själv skapar konto och lägger in, skulle det kanske vara bättre?

**Comment by KodStina** [comment]
Drömscenario!

**Comment by KodStina** [comment]
Just nu håller vi dock på att lägga in konton manuellt, så att du vet :) No stress på denna.

**Comment by thuma** [comment]
Jag har kollat och tror att det smidigaste är att:
CSV filen genereras i BESKen och sedan laddar ni upp den i Scratch?

**Comment by annakod** [comment]
Denna puck skulle behöva tas upp igen. Vore super om Besken kunde generera CSV-filen. Det som behöver vara tydligt i besken är att användarnamn och lösenord är det som står innan och efter kommatecknet i filen t.ex: digistug1, digistug11 = digistug1 är användarnamn och digistug11 är lösenord

**Comment by thuma** [comment]
Ok, tar bollen.

**Comment by thuma** [comment]
Nu finns det i produktion vill ni testa och återkomma om det verkar ok.
