### ISSUE TITLE
Tillgång till besk 

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#52]
Volontärer som vi inte lagt in i besk men som finns med i Slack har tillgång till Slack och ser personuppgifter. Går det att undersöka om det blivit fel någonstans så att bara de som är med i kodstugorna och med i besk ser denna information? Lisa som är admin på Slack har tillgång till Sigmas besk och ska bara se beskarna för lärarkodstugorna.

**Comment by thuma** [comment]
Felet uppstod vid unix timestamp: 1583357666

**Comment by thuma** [comment]
Tillfälligt korrigerat 2020-03-04 14:40:00 UTC
Permanent korrigerat 2020-03-04 14:49:32 UTC

**Comment by thuma** [comment]
Felet uppstod troligen vid: 2020-03-04 11:00:00 UTC

**Comment by thuma** [comment]
Felet uppstod uppstod 2020-03-04T09:34:26 UTC

**Comment by thuma** [comment]
Felet var mycket alvarigt eftersom det gick att logga in utan att fylla i lösenord.
Om man loggade in utan att ange lösenord så blev man inloggad som en Göteborgs Volontär med tillgång till Lärarkodstugan och Sigmna. Jag kan se att 3 olika användare har blivit inloggade på detta sätt. Så Lisa är en av dem. Det finns alltså två ytterligare som råkat ut för denna bugg.

Anledningen till att detta skedde var att inloggning skedde utan att först besöka besken. Jag vet inte hur det kunde ske med säkerhet men jag har lagt in kontroller så att det inte går att logga in utan att först gå till http://besk.kodcentrum.se/ . Har också lagt in kontroller att detta problem inte finns, kontrollen sker varje gång någon utvecklare testar koden till BESKen.
