### ISSUE TITLE
Utskick 

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#56]
Kunna slå på och av utskick utan att behöver radera texten. 
Inte en brådskande åtgärd.

**Comment by SGenheden** [comment]
Så det är de återkommande, veckovisa utskicken du vill kunna stäng av?

**Comment by SGenheden** [comment]
Med de återkommande utskicken, kan jag tänka mig två lösningar:
1. Du går in på fliken Kodstugor och klickar i där att du vill skicka / inte skicka påminnelser
2. Du går in på fliken Utskick målsman och klickar i för varje utskick vilket du vill skicka / inte skicka
Vilket låter bäst?

**Comment by annakod** [comment]
Ja exakt det är utskicken som går ut varje vecka som är påminnelser om kommande kodstugetillfälle, samt lov + inför avslutning. Alternativ 2 låter bäst, tack :) Det vi vill undvika är att behöva ta bort utskickstexterna helt vilket vi behövt göra nu för att "pausa" utskicken genom att skriva nej i textraden.
