### ISSUE TITLE
Nå besk.kodcentrum.se/apply på www.besk.kodcentrum.se/apply 

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#59]
Just nu når man endast formulärs-sidan genom att skriva in https://besk.kodcentrum.se/apply, vore bra att kunna nå formuläret även på www.besk.kodcentrum.se/apply

**Comment by thuma** [comment]
www.besk.kodcentrum.se A 185.157.221.81
www.besk.kodcentrum.se AAAA 2a02:752:0:18::170

**Comment by thuma** [comment]
Ni behöver bara meddela era it människor informationen ovan till DNS så kommer det att gå snabbt att fixa.

**Comment by annakod** [comment]
Hej Martin, vilka it-människor tänker du på och vad står DNS för?

**Comment by thuma** [comment]
@annakod fick di mitt e-post med informationen om vilka som har hand om det?

**Comment by annakod** [comment]
Hej! Fick ditt mail tack, ska ta kontakt med dem.

**Comment by thuma** [comment]
Detta är nu korrigerat.
