### ISSUE TITLE
Kunna radera/arkivera events 

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#61]
Just nu funkar det inte att radera events, de som ligger under "kodstugor", när jag försöker göra det får jag upp felmeddelandet: "Ett fel inträffade v.g. kontakta: hej@kodcentrum.se" 

Det bästa vore att kunna arkivera events så att de hamnar under en egen flik som heter "arkiverade" t.ex. så att vi kan återkomma till informationen från kodstugor t.ex. så att denna inte försvinner helt.

**Comment by thuma** [comment]
Felet beror på att något inte raderas korrekt:
ERROR:server:SERVER FEL:
Traceback (most recent call last):
File "main.py", line 54, in application
resultdata = convert(route(request))
File "main.py", line 151, in route
return kodstugor.handle(request)
File "/home/besk/BESK/managedata/kodstugor.py", line 17, in handle
return delete(request)
File "/home/besk/BESK/managedata/kodstugor.py", line 62, in delete
""", (post_data['id'][0],))
sqlite3.IntegrityError: FOREIGN KEY constraint failed

**Comment by annakod** [comment]
Ok, hur kan vi lösa detta?

**Comment by thuma** [comment]
Det är en bugg så det är löst så fort någon hunnit kolla på varför detta läge uppstår.

**Comment by annakod** [comment]
ok då är jag med :)

**Comment by thuma** [comment]
Nu ska detta vara korrigerat, kodstugor som inte längre är aktiva ska nu gå att radera.
