### ISSUE TITLE
Besk & Explorer

### ISSUE THREAD

**Issue by annakod** [thuma/BESK#66]
Var i kontakt med en samarbetspart som sa att man inte kunde se kodcentrum.besk.se/apply på Explorer-webbläsare, undersök gärna och hur vi åtgärdar detta.

**Comment by thuma** [comment]
Adressen är: besk.kodcentrum.se/apply inte kodcentrum.besk.se/apply

Om användaren använder IE8 eller äldre så funkar det inte. Detta beror på att IE8 och äldre inte har stöd för senare Javascript versioner vi använder versionen från 2015.

**Comment by thuma** [comment]
Det har också varit problem med att systemet vi använder VUE har varit onåbart från den server som de använder. Nu är det uppdaterat så att alla filer ligger på besk servern så att just det felet inte händer igen.
